### ISSUE TITLE
'displayBand' was not declared in this scope

### ISSUE THREAD

**Issue by tmsd2001** [G6EJD/ESP32-8-Octave-Audio-Spectrum-Display#3]
At a new installation of Arduino IDE V 1.9.0-Beta on Windows 10 the error message appears:
`
Arduino\esp32_FFT_V2\esp32_FFT_V2.ino: In function 'void loop()':

esp32_FFT_V2:72:45: error: 'displayBand' was not declared in this scope

       if (i<=2 )             displayBand(0,(int)vReal[i]); // 125Hz

                                             ^

esp32_FFT_V2:73:53: error: 'displayBand' was not declared in this scope

       if (i >2   && i<=4 )   displayBand(1,(int)vReal[i]); // 250Hz

                                                     ^

esp32_FFT_V2:74:53: error: 'displayBand' was not declared in this scope

       if (i >4   && i<=7 )   displayBand(2,(int)vReal[i]); // 500Hz

                                                     ^

esp32_FFT_V2:75:54: error: 'displayBand' was not declared in this scope

       if (i >7   && i<=15 )  displayBand(3,(int)vReal[i]); // 1000Hz

                                                      ^

esp32_FFT_V2:76:55: error: 'displayBand' was not declared in this scope

       if (i >15  && i<=40 )  displayBand(4,(int)vReal[i]); // 2000Hz

                                                       ^

esp32_FFT_V2:77:55: error: 'displayBand' was not declared in this scope

       if (i >40  && i<=70 )  displayBand(5,(int)vReal[i]); // 4000Hz

                                                       ^

esp32_FFT_V2:78:56: error: 'displayBand' was not declared in this scope

       if (i >70  && i<=288 ) displayBand(6,(int)vReal[i]); // 8000Hz

                                                        ^

esp32_FFT_V2:79:47: error: 'displayBand' was not declared in this scope

       if (i >288           ) displayBand(7,(int)vReal[i]); // 16000Hz

                                               ^

exit status 1
'displayBand' was not declared in this scope
`

I have the same Programm running on the same ESP Model, but this was upload with a other Arduino Version which I already deleted.

**Comment by tobozo** [comment]
you can move the displayBand() function earlier in the code (currently it's at the end of the sketch) or provide a signature after the includes (e.g.  just before `void setup()`) so the compiler is happy : 

`void displayBand(bool channel, int band, int dsize);`

**Comment by tmsd2001** [comment]
I move it before setup, now i can compile it.
