### ISSUE TITLE
I2S microphones

### ISSUE THREAD

**Issue by bertrik** [G6EJD/ESP32-8-Octave-Audio-Spectrum-Display#4]
Not really an issue, but have you considered using a digital I2S microphone?
These microphones directly output a digital signal, in I2S format.

Example of how to use them:
https://github.com/maspetsberger/esp32-i2s-mems

And my own project:
https://revspace.nl/EspAudioSensor

I'd like to do a periodic sampling of ambient audio and then do an FFT on it. For example, as a kind of environmental audio sensor. The FFT should allow me to tell me what kind of sounds is around, be able to correct for the microphone/housing, and do an A-weighting to get subjective noise level.

**Comment by G6EJD** [comment]
I have not as I don’t have an I2C microphone, but I can see how an instantaneous sample can be taken for onward FFT sampling, or conversely the input array can be filled with samples in one line. It just takes time to do all this, time is short unfortunately.
Incidentally 
I read your requirement document and in the FFT section, you seem to have omitted how to get the vector value, thus:
The energy in each octave is calculated by applying an FFT (fast fourier transform) on the audio data. The FFT takes in real values and outputs complex values. The intensity in each octave band is by determined by summing the energy in a set of FFT frequency band 'bins'. The energy in each bin is calculated as the real part squared plus the imaginary part squared, added then the square-root is taken to yield the final vector value or energy.

**Comment by G6EJD** [comment]
Out of interest when I tested the FFT display using my function generator it gives a flat frequency response from 20/20,000Hz which is the range I tested for, it can do better than that and the ADC analogue microphone can perform as well as any mems unit provided it has a good response. The 12-bit ADC is very fast on the ESP32.

**Comment by bertrik** [comment]
Hi, thanks for your quick reply!

I didn't realise the built-in ADC of the ESPs was fast and accurate enough for sampling audio.
I would still like to try this with a digital I2S microphone, also just for getting some experience interfacing them with an ESP. I like how they output a fully digital signal, although I'm a bit worried how well a several MHz signal carries over a "dupont" cable. Aliexpress sells these microphones for under E3,-

So, maybe you'll see a pull request from me with an example using an I2S microphone.

**Comment by G6EJD** [comment]
There are t many practical examples of using I2S bus devices or accompanying library support so much of the results will be hit-and-miss, if I get the test me I’ll try out one of the devices, for me the outcome is all about the FFT rather than the sampling process, I found the cheap microphones more than adequate for HF radio decoding of audio and morse code, so that’s as far as I went. I have no idea how good the i2s microphone responses are, maybe not necessarily perfect but I see a wide omnidirectional response which could be useful. Specification sheets seem few and far apart.

**Comment by G6EJD** [comment]
I had a look at the device INMP441 to be honest, it's not that impressive, it's flat frequency response is from 200Hz to ~4KHz and -3dB points are 60-15KHz. It samples at maximum 48KHz so a data rate of 64xFs or 3.072Mbps or 16KHz equating to 1Mbps, only a trial would determine what transmission line would be required, certainly a coaxial cable would be more than OK, Maybe there are better devices around that are designed for more than just speech.

**Comment by bertrik** [comment]
Do you have a datasheet for the microphone you're using? I looked at the Aliexpress link, but there's no type information there for the actual microphone.

**Comment by G6EJD** [comment]
It’s a standard electret type, cost about€1 if that, unfortunately I’ve never seen a data sheet for the microphone element, but using my Bose speaker and function generator I was able to demonstrate it operating across the 8-octaves up to 16KHz. Although I did not do it, software can be used to flatten its response depending on which FFT detection band is greater than zero, once its response has been measured, which I have not done, but could, this would make a quite flat FFT response possible and remove microphone shortcomings.

**Comment by Cysign** [comment]
Hey G6EJD, did you find any code sample for the INMP441?
Just orderes one as it's incredibly cheap to test it with this FFT lib.
Hope I can get it run, I'm only experienced using Atmel MCUs yet. Did you run into problems with the I2S microphone running this library?

**Comment by G6EJD** [comment]
I have not used an I2C device yet, plus getting a sample at a specific time may not be as easy as you think because the sampling rate is so high so now you need to sample the samples at defined intervals. Good luck. Please share your code when done.

**Comment by bertrik** [comment]
@Cysign I'm confident it's actually not so difficult to the get an I2S microphone running with the spectrum analyzer. Basically just set I2S up once, defining which pins to use for i2s, which i2s format, sample rate etc. Then you can just request X samples from the the microphone. The data is always in a kind of 32-bit fixed point format as I understand.

Maybe I can work on that a little bit this weekend in my fork of the library.

**Comment by G6EJD** [comment]
Indeed yes, interfacing and getting the data should be straightforward but the data samples need to be contiguous for the FFT and you’ll get a lot of data that then needs transposing to the correct type and then repeat.
When I looked at those microphones their response was somewhat basic and there was no advantage over an electret type, certainly no bandwidth improvements and they are really for speech rather than broad range applications, they won’t be seen anytime soon in a studio environment for example. I like the electret types because they consume nearly zero power and they are directional.

**Comment by Cysign** [comment]
Just ordered one overseas - as I finally wanted to get started with DSP.
An example would be highly appreciated, as I'm a beginner in this field, tough I've read some a lot baout DSP ;)
